name: tudatpy-docs-readthedocs
channels:
  - conda-forge
  - tudat-team/label/dev
  - tudat-team
dependencies:
  # All standard tudat-bundle deps are needed for sphinx-documentation for tudatpy.
  - python=3.8
  - numpy
  - matplotlib # for tudat.plotting
  - basemap # for tudat.plotting
  - basemap-data-hires # for tudat.plotting
  # Other doc related
  - jinja2
  - yaml
  #- cmake
  - pydantic=1.10.9
  - numpydoc
  - tudatpy=0.8.0.dev7
  - tudat=2.13.0.dev10
  - boost-cpp=1.84.0
  - pip
  - pip:
     - nbsphinx
     - sphinxcontrib-napoleon
     - sphinx_rtd_theme
     - sphinxcontrib-fulltoc
     - sphinxcontrib-bibtex
     - furo
     - sphinx_copybutton